# Data Types

In [ ]:
import numpy as np

boolean = np.bool_(True)
print(boolean)
print(type(boolean))

True
<class 'numpy.bool'>


In [ ]:
import numpy as np

string = np.bytes_("Lorem ipsum dolor sit amet")

print(string)
print(type(string))

b'Lorem ipsum dolor sit amet'
<class 'numpy.bytes_'>


In [ ]:
import numpy as np

string = np.str_("Lorem ipsum dolor sit amet")

print(string)
print(type(string))

Lorem ipsum dolor sit amet
<class 'numpy.str_'>


In [ ]:
import numpy as np
# 32 bits
integer = np.intc(-102)
# 32 bits unsigned
uinteger = np.uintc(102)
# 64 bit
long = np.int_(848484884)
# 64 bit unsigned
ulong = np.uint(3829039293290)

print(integer, type(integer))
print(uinteger, type(uinteger))
print(long, type(long))
print(ulong, type(ulong))


-102 <class 'numpy.int32'>
102 <class 'numpy.uint32'>
848484884 <class 'numpy.int64'>
3829039293290 <class 'numpy.uint64'>


In [ ]:
import numpy as np

# 64 bits
floating_point = np.float64(10002.34)
# 32 bits
floating_point2 = np.float32(3994.34)

print(floating_point, type(floating_point))
print(floating_point2, type(floating_point2))


10002.34 <class 'numpy.float64'>
3994.34 <class 'numpy.float32'>


In [ ]:
import numpy as np

int8 = np.int8(20)
int16 = np.int16(1000)
uint8 = np.uint8(34)
uint16 = np.uint16(344)
float16 = np.float16(16)

print(int8, type(int8))
print(int16, type(int16))
print(uint8, type(uint8))
print(uint16, type(uint16))
print(float16, type(float16))

20 <class 'numpy.int8'>
1000 <class 'numpy.int16'>
34 <class 'numpy.uint8'>
344 <class 'numpy.uint16'>
16.0 <class 'numpy.float16'>


# Other Ways to Declare Types

In [ ]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,0])

print(array)
print(type(array))
print(array.dtype)

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int64


In [ ]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,0], dtype=np.int8)

print(array)
print(type(array))
print(array.dtype)

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int8


In [ ]:
import numpy as np

array = np.array(["1","234","1"], dtype=np.bytes_)

print(array)
print(type(array))
print(array.dtype)

[b'1' b'234' b'1']
<class 'numpy.ndarray'>
|S3


In [ ]:
import numpy as np

array = np.array(["abc","def","ghi"], dtype="S3")

print(array)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)

[b'abc' b'def' b'ghi']
|S3
3
9


In [ ]:
import numpy as np

array = np.array([1, 2, 3], dtype="i2")

print(array)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)

[1 2 3]
int16
2
6


# Creating Our Types

In [ ]:
import numpy as np

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age


array = np.array(
    [
        Person("Fernando", 45),
        Person("Rodrigo", 23)
    ]
)

print(array)
print(type(array))
print(array.dtype, end="\n\n")
print(array[0].name, array[1].age)

<class 'numpy.ndarray'>
object

Fernando 23


In [ ]:
import numpy as np

person_type = np.dtype([('name', 'S10'), ('age', 'i4')])

array = np.array(
    [
        ("Fernando", 45),
        ("Rodrigo", 23)
    ],
    dtype=person_type
)

print(array)
print(type(array))
print(array.dtype, end="\n\n")

[(b'Fernando', 45) (b'Rodrigo', 23)]
<class 'numpy.ndarray'>
[('name', 'S10'), ('age', '<i4')]



# Array Properties

In [ ]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,0])

print(array)
print(array.ndim)
print(array.size)
print(len(array))
print(array.shape)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)


[1 2 3 4 5 6 7 8 9 0]
1
10
10
(10,)
int64
8
80


In [ ]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array)
print(array.ndim)
print(array.size)
print(len(array))
print(array.shape)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9
3
(3, 3)
int64
8
72


In [ ]:
import numpy as np

person_type = np.dtype([('name', 'S10'), ('age', 'i4')])

array = np.array(
    [
        ("Fernando", 45),
        ("Rodrigo", 23)
    ],
    dtype=person_type
)

print(array)
print(array.ndim)
print(array.size)
print(array.shape)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)

[(b'Fernando', 45) (b'Rodrigo', 23)]
1
2
(2,)
[('name', 'S10'), ('age', '<i4')]
14
28


# Creating Populated Objects

In [ ]:
import numpy as np

array1 = np.zeros(9)
array2 = np.ones(3)
array3 = np.empty(6)
array4 = np.identity(4)

print(array1, end="\n\n")
print(array2, end="\n\n")
print(array3, end="\n\n")
print(array4, end="\n\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1.]

[4.24592180e-315 0.00000000e+000 4.26749763e-315 7.16395186e-322
 4.26749747e-315 0.00000000e+000]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [ ]:
import numpy as np

array1 = np.zeros((3,3))
array2 = np.ones((4,4))

print(array1, end="\n\n")
print(array2, end="\n\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [ ]:
import numpy as np

array1 = np.arange(9)
array2 = np.arange(4, 16)

print(array1, end="\n\n")
print(array2, end="\n\n")

[0 1 2 3 4 5 6 7 8]

[ 4  5  6  7  8  9 10 11 12 13 14 15]



In [ ]:
import numpy as np

array1 = np.arange(2,16+1,2)

print(array1, end="\n\n")

[ 2  4  6  8 10 12 14 16]



In [ ]:
import numpy as np

array = np.full((4,4), 10)

print(array)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [ ]:
import numpy as np

array_float = np.random.rand(4,4)
array_int = np.random.randint(5,10, (5,5))

print(array_float)
print(array_int)

[[0.30425118 0.86772767 0.16344101 0.70999095]
 [0.74719461 0.18537634 0.84473789 0.70409072]
 [0.46230697 0.5594673  0.64964317 0.17152633]
 [0.45627741 0.26576745 0.64405424 0.38461225]]
[[9 8 7 5 5]
 [9 7 6 8 6]
 [6 5 5 7 5]
 [8 7 6 5 7]
 [6 8 6 6 8]]


# List Comprehension

In [ ]:
import numpy as np

array = np.array([i for i in range(0,10)])

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

array = np.array(
  [
    [i for i in range(0,3)],
    [i for i in range(3,6)],
    [i for i in range(6,9)],
  ]
)

print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Slicing

In [ ]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10])

print(array[2])
print(array[2:4])

3
[3 4]


In [ ]:
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array, end='\n\n')

print(array[2])
print(array[2][2])
print(array[2,2])
print(array[1:3])
print(array[2,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]
9
9
[[4 5 6]
 [7 8 9]]
[8 9]


In [ ]:
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array, end='\n\n')

print(array[2, :])
print(array[:, 2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]
[3 6 9]


In [ ]:
import numpy as np

array = np.array([[1,2,3,4],[5,6,7,8]])
print(array, end='\n\n')

print(array[1, :])
print(array[:, 1])

[[1 2 3 4]
 [5 6 7 8]]

[5 6 7 8]
[2 6]


In [ ]:
import numpy as np

array = np.array(
  [
    [1,2,3,4,5,6,7,8,9],
    [10,11,12,13,14,15,16,17,18],
    [19,20,21,22,23,24,25,26,27]
  ]
)
print(array, end='\n\n')

print(array[1, 0:8:2])

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]

[10 12 14 16]


# Iterating Over Arrays

In [ ]:
import numpy as np

array = np.array([1,2,3,4])

for i in array:
  print(i)

1
2
3
4


In [ ]:
import numpy as np

array = np.array([[1,2,3,4], [5,6,7,8]])

for i in array:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np

array = np.array([[1,2,3,4], [5,6,7,8]])

print(array, end='\n\n')

for x in np.nditer(array, order='F'):
  print(x)


[[1 2 3 4]
 [5 6 7 8]]

1
5
2
6
3
7
4
8


# Inserting and Removing Elements

In [ ]:
import numpy as np

array = np.array([[1,2,3], [5,6,7], [7,8,9]])
array[0]=[1,2,4]
array[1, 1:3] = [0,0]
array[0,0] = 10
print(array)

[[10  2  4]
 [ 5  0  0]
 [ 7  8  9]]


In [ ]:
import numpy as np

array = np.array([[1,2,3], [5,6,7], [7,8,9]])
array[:,2] = [0,0,0]
print(array)


[[1 2 0]
 [5 6 0]
 [7 8 0]]


In [ ]:
import numpy as np

array = np.array([1,2,3,4])
array2 = np.append(array, [5,6,7,8])
print(array)
print(array2)

[1 2 3 4]
[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np

array = np.array([[1,2,3], [5,6,7], [7,8,9]])
print(array, end='\n\n')

array2 = np.append(array, [5,6,7])
print(array2)

[[1 2 3]
 [5 6 7]
 [7 8 9]]

[1 2 3 5 6 7 7 8 9 5 6 7]


In [ ]:
import numpy as np

array = np.array([[1,2,3], [4,5,6], [7,8,9]])
array1 = np.append(array, [[10,11,12]], axis=0)
array2 = np.append(array, [[10], [11], [12]], axis=1)

print(array, end='\n\n')
print(array1, end='\n\n')
print(array2, end='\n\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]



In [ ]:
import numpy as np

array = np.array([1,2,3])

array = np.insert(array, 1,10)

print(array)


[ 1 10  2  3]


In [ ]:
import numpy as np

array = np.array([[1,2,3], [7,8,9], [10,11,12]])

array1 = np.insert(array, 1, [4,5,6], axis=0)
array2 = np.insert(array, 1, [4,5,6], axis=1)
print(array1, end='\n\n')
print(array2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  4  2  3]
 [ 7  5  8  9]
 [10  6 11 12]]


In [ ]:
import numpy as np

array = np.array([[1,2,3], [7,8,9], [10,11,12]])

array1 = np.delete(array, 1, axis=0)
array2 = np.delete(array, 1, axis=1)
print(array1, end='\n\n')
print(array2)

[[ 1  2  3]
 [10 11 12]]

[[ 1  3]
 [ 7  9]
 [10 12]]


# Copying an Array

In [ ]:
import numpy as np

array = np.array([1,2,3])
copy_array = array
copy_array[0] = 0
print(array)

[0 2 3]


In [ ]:
import numpy as np

array = np.array([1,2,3])
copy_array = array.copy()
copy_array[0] = 0
print(array)

[1 2 3]


# Changing Dimensions

In [ ]:
import numpy as np

array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array, end='\n\n')
array = array.reshape(9)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

array = np.array([i for i in range(0,27)])
print(array, end='\n\n')

array = array.reshape(3,9)
print(array, end='\n\n')

array = array.reshape(9,3)
print(array, end='\n\n')

array = array.reshape(3,3,3)
print(array, end='\n\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]



In [ ]:
import numpy as np

array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array, end='\n\n')
array = array.flatten()
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


# Array Operations

In [ ]:
import numpy as np

array1 = np.array([1,2,3])
array2 = np.array([2,4,6])

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)
print(array1 * array2)
print(array1 ** array2)
print(array1 // array2)

[3 6 9]
[-1 -2 -3]
[0.5 0.5 0.5]
[ 2  8 18]
[  1  16 729]
[0 0 0]


In [ ]:
import numpy as np

array1 = np.array([1,1,1])
array2 = np.array([[2,4,6],[1,2,3]])

print(array1 + array2)

[[3 5 7]
 [2 3 4]]


In [ ]:
import numpy as np

array1 = np.array([1,1,1])
array2 = np.array([[2,4,6],[1,2,3]])
array3 = np.array([[2,4,6],[1,2,3], [3,4,5]])

print(array1 + array2, end='\n\n')
print(array1 + array3)

[[3 5 7]
 [2 3 4]]

[[3 5 7]
 [2 3 4]
 [4 5 6]]


In [ ]:
import numpy as np

array1 = np.array([1,2,3])

print(array1 + 2)
print(array1 - 2)

[3 4 5]
[-1  0  1]


In [ ]:
import numpy as np

array1 = np.array([10,20,30,5])
array2 = np.array([20,40,10,5])

print(array1 > array2)
print(array1 == array2)
print(array1 != array2)

[False False  True False]
[False False False  True]
[ True  True  True False]


In [ ]:
import numpy as np

array1 = np.array([10,20,30,5])
array2 = np.array([20,40,10,5])
array3 = np.array([10,20,30,5])

print(np.array_equal(array1, array2))
print(np.array_equal(array1, array3))

False
True


# Combining Arrays

In [ ]:
import numpy as np

array1 = np.array([10,20,30,5])
array2 = np.array([20,40,10,5])

array12 = np.concatenate((array1, array2), axis=0)
print(array12)

[10 20 30  5 20 40 10  5]


In [ ]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])

array12 = np.concatenate((array1, array2), axis=0)
print(array12, end='\n\n')

array12 = np.concatenate((array1, array2), axis=1)
print(array12)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
import numpy as np

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

array12r = np.vstack((array1, array2))
array12c = np.hstack((array1, array2))

print(array12r)
print(array12c)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])

array12r = np.vstack((array1, array2))
array12c = np.hstack((array1, array2))

print(array12r, end='\n\n')
print(array12c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Splitting Arrays

In [ ]:
import numpy as np

array = np.array([1,2,3,4,5,6])
print(np.split(array,1))
print(np.split(array,2))
print(np.split(array,3))

[array([1, 2, 3, 4, 5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

array = np.array([[1,2,3,4],[4,5,6,7]])
print(np.split(array,2))

[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]])]


In [ ]:
import numpy as np

array = np.array([1,2,3,4,5,6])
array1 = np.array_split(array,2)
array2 = np.array_split(array,3)
array3 = np.array_split(array,4)

print(array, end='\n\n')
print(array1, end='\n\n')
print(array2, end='\n\n')
print(array3, end='\n\n')

[1 2 3 4 5 6]

[array([1, 2, 3]), array([4, 5, 6])]

[array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5]), array([6])]



In [ ]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
array1 = np.array_split(array,2)
array2 = np.array_split(array,3)
array3 = np.array_split(array,4)

print(array, end='\n\n')
print(array1, end='\n\n')
print(array2, end='\n\n')
print(array3, end='\n\n')

[[1 2 3]
 [4 5 6]]

[array([[1, 2, 3]]), array([[4, 5, 6]])]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]



In [ ]:
import numpy as np

array = np.array([[1,2,3],[4,5,6], [7,8,9]])
array1 = np.hsplit(array,3)

print(array1)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


# Filtering Elements

In [ ]:
import numpy as np

array = np.array([1,3,4,2,7,4])

array_find = np.where(array >= 4)
print(array_find)

(array([2, 4, 5]),)


In [ ]:
import numpy as np

array = np.array([1,3,4,2,7,4])

array_find = np.where((array == 4) | (array == 7))
print(array_find)

(array([2, 4, 5]),)


In [ ]:
import numpy as np

array = np.array([1,-1,-3,0,6,3,-78])

array_find = np.where((array > 0) & (array < 10))
print(array_find)

(array([0, 4, 5]),)


In [ ]:
import numpy as np

array = np.array([1,3,4,2,7,4])

array_find = np.any(array==1)
print(array_find)

True


In [ ]:
import numpy as np

array = np.array([1,3,4,2,7,4])

array_find = np.any((array>0) & (array<10))
print(array_find)

True


In [ ]:
import numpy as np

array = np.array([1,3,4,2,7,4])

array_find = np.all(array>0)
print(array_find)

True


In [ ]:
import numpy as np

array = np.array([1,0,1,1,1,0,0])
filter = array ==1
filter_array = array[filter]

print(filter_array)

[1 1 1 1]


In [ ]:
import numpy as np

array = np.array([1,0,1,1,1,0,2])
filter = (array==1) | (array==2)
filter_array = array[filter]

print(filter_array)

[1 1 1 1 2]


In [ ]:
import numpy as np

array = np.array([1,0,1,1,1,0,2])
filtered_array = np.array([i for i in array if i==0])

print(filtered_array)

[0 0]


# Sorting

In [ ]:
import numpy as np

array = np.array([4,1,3,2])
print(np.sort(array, kind='quicksort'))

[1 2 3 4]


In [ ]:
import numpy as np

array = np.array([[38,2,1],[5,5,4]])
print(np.sort(array, axis=0), end='\n\n')
print(np.sort(array, axis=1))

[[ 5  2  1]
 [38  5  4]]

[[ 1  2 38]
 [ 4  5  5]]


# Arithmetic Operations

In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,18])
arr2 = np.array([1,2,3,4,5,6,3])

array1 = np.add(arr1, arr2)
array2 = np.subtract(arr1, arr2)
array3 = np.multiply(arr1, arr2)
array4 = np.divide(arr1, arr2)

print(array1)
print(array2)
print(array3)
print(array4)

[ 2  4  6  8 10 12 21]
[ 0  0  0  0  0  0 15]
[ 1  4  9 16 25 36 54]
[1. 1. 1. 1. 1. 1. 6.]


In [ ]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

array1 = np.add(arr1, arr2)
array2 = np.subtract(arr1, arr2)
array3 = np.multiply(arr1, arr2)
array4 = np.divide(arr1, arr2)

print(array1)
print(array2)
print(array3)
print(array4)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,18])
arr2 = np.array([1,2,3,4,5,6,3])

array1 = np.divide(arr1, arr2)
array2 = np.floor_divide(arr1, arr2)

print(array1)
print(array2)

[1. 1. 1. 1. 1. 1. 6.]
[1 1 1 1 1 1 6]


In [ ]:
import numpy as np

arr1 = np.array([1,2])
arr2 = np.array([2,4])

array1 = np.power(arr1, arr2)
print(array1)

[ 1 16]


In [ ]:
import numpy as np

arr1 = np.array([2,2, 100])
arr2 = np.array([2,3,31])

array1 = np.mod(arr1, arr2)
print(array1)

[0 2 7]


In [ ]:
import numpy as np

arr1 = np.array([2,2, 100])
arr2 = np.array([2,3,31])

array1 = np.divmod(arr1, arr2)
print(array1)

(array([1, 0, 3]), array([0, 2, 7]))


In [ ]:
import numpy as np

arr1 = np.array([4,25, 100])

array1 = np.sqrt(arr1)
print(array1)

[ 2.  5. 10.]


In [ ]:
import numpy as np

arr1 = np.array([3.14159, 2.71])

array1 = np.around(arr1, 2)
print(array1)

[3.14 2.71]


In [ ]:
import numpy as np

arr1 = np.array([3.14159, 2.71])

array1 = np.floor(arr1)
print(array1)

[3. 2.]


In [ ]:
import numpy as np

arr1 = np.array([3.14159, 2.71])

array1 = np.ceil(arr1)
print(array1)

[4. 3.]


# Accumulators

In [ ]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
array_sum = np.sum(array)
print(array_sum)

21


In [ ]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
array_sum = np.sum(array, axis=1)
print(array_sum)

[ 6 15]


In [ ]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
array_sum = np.cumsum(array)
print(array_sum)

[ 1  3  6 10 15 21]


In [ ]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
array_sum = np.cumprod(array)
print(array_sum)

[  1   2   6  24 120 720]


In [ ]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])
array1 = np.cumprod(array, axis=0)
array2 = np.cumprod(array, axis=1)
print(array1)
print(array2)

[[ 1  2  3]
 [ 4 10 18]]
[[  1   2   6]
 [  4  20 120]]


In [ ]:
import numpy as np

array = np.array([1,2,3,4,5,6])

print(np.amin(array))
print(np.amax(array))

1
6


In [ ]:
import numpy as np

array = np.array([1,-2,-3,-4,5,6])

print(np.abs(array))

[1 2 3 4 5 6]


In [ ]:
import numpy as np

array = np.array([[1,4,8],[4,3,6]])

print(np.amin(array))
print(np.amin(array, axis=1))
print(np.amin(array, axis=0))

1
[1 3]
[1 3 6]


# Union, Intersection, and Removing Duplicates

In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6,7])

newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6 7]


In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6,7])

newarr = np.intersect1d(arr1, arr2)
print(newarr)

[3 4]


In [ ]:
import numpy as np

arr1 = np.array([1,2,2,3,4,3,5,5,5,4])

newarr = np.unique(arr1)
print(newarr)

[1 2 3 4 5]


# Activities


Create an array with the numbers from 0 to 9, using only one dimension.

In [ ]:
import numpy as np

array = np.arange(10)

print(array)

[0 1 2 3 4 5 6 7 8 9]


Create an array with the numbers from 0 to 9, as in the previous exercise, but use List Comprehensions.


In [ ]:
import numpy as np

array = np.array([i for i in range(0,10)])

print(array)

[0 1 2 3 4 5 6 7 8 9]


Create an array with the numbers from 0 to 8, using two dimensions, with 3 rows (3x3).

In [ ]:
import numpy as np

array = np.arange(9).reshape((3,3))

print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a float array with 10 numbers of your choice, using 32 bits/4 bytes.


In [ ]:
import numpy as np

array = np.arange(0,9, dtype='f4')
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


Create an array with the numbers from 1 to 20, choosing the data type that uses the least amount of memory. Then print how many bytes it occupies.

In [ ]:
import numpy as np

array = np.arange(1,21, dtype=np.int8)
print(array)
print(array.nbytes)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20


Create a 2x2 matrix and print the first element of the first row and the last element of the last row.

In [ ]:
import numpy as np

array = np.random.randint(1,5,(2,2))
print(array)

print(array[0][0])
print(array[1][1])

[[1 3]
 [4 4]]
1
4


Generate a 3x3 array with random integers between 5 and 20. Then print the first column and the last row.

In [ ]:
import numpy as np

array = np.random.randint(5,20,(3,3))
print(array)

print(array[:,0])
print(array[2,:])

[[ 8  7 12]
 [ 6 19 19]
 [11 11 18]]
[ 8  6 11]
[11 11 18]


Create a random 3x3 matrix. Iterate through it row by row with a loop and print the sum of each row.

In [ ]:
import numpy as np

array = np.random.randint(1,50,(3,3))
print(array, end='\n\n')
for line in array:
  print(np.sum(line))

[[44 19 42]
 [19  6 27]
 [25 44  1]]

105
52
70


Generate an array containing the even numbers from 0 to 100 using list comprehension.

In [ ]:
import numpy as np

array = np.array([i for i in range(0,101) if i%2 == 0])

print(array)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Create a 4x9 array with arbitrary values, then reshape it to dimensions 36 and 6x6.

In [ ]:
import numpy as np

array = np.random.randint(0,10, (4,9))
print(array.reshape(36))
print(array.reshape((6,6)))

[1 2 1 4 6 8 2 9 1 6 4 6 3 2 5 1 3 3 8 8 7 5 7 0 6 2 3 3 6 8 9 8 6 5 4 4]
[[1 2 1 4 6 8]
 [2 9 1 6 4 6]
 [3 2 5 1 3 3]
 [8 8 7 5 7 0]
 [6 2 3 3 6 8]
 [9 8 6 5 4 4]]


Create a function that receives three arrays with the same shape and returns them concatenated into a single array. If the matrices received do not have the same shape, raise an exception.

In [ ]:
import numpy as np

def combine_arrays(arr1, arr2, arr3):
  if (arr1.shape != arr2.shape) or (arr1.shape != arr3.shape):
    raise Exception("The formats are different")
  return np.concatenate((arr1, arr2, arr3))

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.array([7,8,9])

print(combine_arrays(array1, array2, array3))

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

def combine_arrays(arr1, arr2, arr3):
  if (arr1.shape != arr2.shape) or (arr1.shape != arr3.shape):
    raise Exception("The formats are different")
  return np.concatenate((arr1, arr2, arr3))

array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6])
array3 = np.array([7,8,9])

print(combine_arrays(array1, array2, array3))

Exception: The formats are different

Create a function that splits an array into N pieces, but keeps only the absolute values of the elements in the array.

In [ ]:
import numpy as np

def split_absolute(arr, n):
  arr = np.array_split(arr, n)
  arr = np.abs(arr)
  return arr

array1 = np.array([1,2,3,-4,5,-7])
print(split_absolute(array1, 2))

[[1 2 3]
 [4 5 7]]


Create a function that receives an array and returns the number of positive numbers it contains.

In [ ]:
import numpy as np

def count_positives(arr):
  return len(np.where(arr>0)[0])

array = np.array([1,2,3,-4,5,-7])
print(count_positives(array))

4


Create a function that receives a matrix and returns the indices of the numbers that are divisible by 3.

In [ ]:
import numpy as np

def find_indices_divisible_by_3(arr):
  return np.where(arr % 3 ==0)[0]

array = np.array([4,5,6,7,8,9])
print(find_indices_divisible_by_3(array))

[2 5]


Create a function that determines whether an array contains negative numbers.

In [ ]:
import numpy as np

def has_negatives(arr):
  return np.any(arr<0)

array = np.array([4,5,-6,7,8])
print(has_negatives(array))

True


In [ ]:
import numpy as np

def has_negatives(arr):
  return np.any(arr<0)

array = np.array([4,5,6,7,8])
print(has_negatives(array))

False


Create a function that removes negative numbers from an array.

In [ ]:
import numpy as np

def remove_negatives(arr):
  filter = arr >= 0
  return arr[filter]

array = np.array([1,-5,5,4,3,-2,-1])
print(remove_negatives(array))

[1 5 4 3]


Create a function that receives a starting number, an ending number, and an array. The function should return a new array containing only the numbers within this range.

In [ ]:
import numpy as np

def filter_values(arr, start, end):
  filter = (arr >= start) & (arr <= end)
  return arr[filter]

array = np.array([i for i in range(-10,11)])
print(array)

print(filter_values(array, 0, 7))

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]
[0 1 2 3 4 5 6 7]


Create a function that sorts a matrix and removes all odd numbers.

In [ ]:
import numpy as np

def sort_evens(arr):
  arr = np.sort(arr)
  filter = arr % 2 ==1
  return arr[filter]

array = np.random.randint(0,10,(100))
print(sort_evens(array))

[1 1 1 1 1 1 1 1 3 3 3 3 3 3 5 5 5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 7 7 7 7 7 9
 9 9 9 9 9 9 9 9]


Do the same as the previous exercise, but also remove duplicate values.

In [ ]:
import numpy as np

def sort_unique_evens(arr):
  arr = np.sort(arr)
  filter = arr % 2 ==1
  return np.unique(arr[filter])

array = np.random.randint(0,10,(100))
print(sort_unique_evens(array))

[1 3 5 7 9]
